-- Generated by the Catala compiler, do not edit!
import CatalaRuntime
open CatalaRuntime

structure Individual where
  income : Int
  number_of_children : Int
  deriving Repr, DecidableEq, Inhabited

structure IncomeTaxComputation where
  income_tax : Int
  deriving Repr, DecidableEq, Inhabited

structure TestTaxComputation where
  result : IncomeTaxComputation
  deriving Repr, DecidableEq, Inhabited

-- Scope-input structs (to_lean.ml bug: not yet emitted automatically)
structure IncomeTaxComputation_in where
  individual_in : Individual
  deriving Inhabited

structure TestTaxComputation_in where
  result_in : IncomeTaxComputation
  deriving Inhabited

def loc : (Array SourcePos) :=
  #[SourcePos.dummy, SourcePos.dummy, SourcePos.dummy, SourcePos.dummy,
    SourcePos.dummy, SourcePos.dummy, SourcePos.dummy, SourcePos.dummy,
    SourcePos.dummy]

def income_tax_computation (income_tax_computation_in : IncomeTaxComputation_in) : IncomeTaxComputation :=
  let individual : Individual := income_tax_computation_in.individual_in
  let tax_rate : (Option ((Rat × SourcePos))) := catalaHandleExceptions
    #[some ((1/5 : Rat), catala_o_array_nth 4 loc),
      if ((individual.number_of_children) >= (2 : Int))
        then (some ((3/20 : Rat), catala_o_array_nth 5 loc))
        else none]
  let income_tax : Int := match some (catala_o_mult_mon_rat (individual.income)
      (match tax_rate with
       | none => catalaFatalError "NoValue"
       | some arg => (let (x, _) := arg; x)),
      catala_o_array_nth 1 loc) with
    | none => catalaFatalError "NoValue"
    | some arg => (let (x, _) := arg; x)
  { income_tax := income_tax }

def test_tax_computation (test_tax_computation_in : TestTaxComputation_in) : TestTaxComputation :=
  let individual : (Option ((Individual × SourcePos))) :=
    some ({ income := (8000000 : Int), number_of_children := (2 : Int) },
          catala_o_array_nth 6 loc)
  let result : IncomeTaxComputation := match some (
      let result__1 : IncomeTaxComputation := income_tax_computation
        { individual_in :=
            match individual with
            | none => catalaFatalError "NoValue"
            | some arg => (let (x, _) := arg; x) }
      let result__2 : IncomeTaxComputation := { income_tax := result__1.income_tax }
      if true then result__2 else result__2,
      catala_o_array_nth 7 loc) with
    | none => catalaFatalError "NoValue"
    | some arg => (let (x, _) := arg; x)
  { result := result }
